CREATE DATABASE concesionario_pro;
USE concesionario_pro;

CREATE TABLE coches(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR (50),
    MODELO VARCHAR (50),
    PRECIO DECIMAL (10,2),
    STOCK INT,
    IMAGEN VARCHAR (100) DEFAULT 'default.jpg',
    DESTACADO BOOLEAN DEFAULT 0
);    

CREATE TABLE piezas(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (100),
    REFERENCIA VARCHAR (20) UNIQUE,
    PRECIO DECIMAL (10,2),
    STOCK INT,
    UBICACION VARCHAR(10)
);

CREATE TABLE citas(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE VARCHAR (100),
    MATRICULA VARCHAR (15),
    DESCRIPCION TEXT,
    FECHA DATE,
    ESTADO ENUM('PENDIENTE','EN PROCESO','FINALIZADA') DEFAULT 'PENDIENTE'  
);

CREATE TABLE empleados(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (100),
    CARGO VARCHAR (50),
    EMAIL VARCHAR (100),
    SUELDO DECIMAL (10,2)
);

INSERT INTO coches (MARCA, MODELO, PRECIO, STOCK, DESTACADO) VALUES
('Toyota', 'Corolla', 20000.00, 10, 1),
('Ford', 'Focus', 18000.00, 15, 0),
('Honda', 'Civic', 22000.00, 8, 1);

INSERT INTO empleados (NOMBRE, CARGO, EMAIL, SUELDO) VALUES
('Juan Pérez', 'Gerente', 'juan.perez@example.com', 3500.00),
('María López', 'Vendedora', 'maria.lopez@example.com', 2800.00);